"""Generate public/js/char_rig_data.js from Marco's raw build_characters iter2 GLBs.

The live GLBs (public/assets/characters/{male,female}.glb) were flattened by
normalize_export.py (181/223 top-level meshes, no joints). Marco's raw sources
still carry build_characters.py's joint tree (Root > Hips > Spine > Chest > ...).
This script reads, per gender:
  - each joint's world position (source space) and parent
  - each mesh's parent joint
and maps joint positions into the live GLB's space (uniform scale + offset,
least-squares fit on per-mesh bounding boxes; the residual is printed).

The character GLBs are NOT modified. Run from the repo root:
  python3 tools/marco_char_delta/gen_rig_map.py
"""
import json
import struct
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
SOURCES = {
    "male": Path("/workspace/marco-char-delta4/male_belizean_build_v2.glb"),
    "female": Path("/workspace/marco-char-delta4/female_trinidadian_build_v2.glb"),
}
LIVE = {
    "male": REPO / "public/assets/characters/male.glb",
    "female": REPO / "public/assets/characters/female.glb",
}
OUT = REPO / "public/js/char_rig_data.js"


def load_glb(p):
    d = Path(p).read_bytes()
    cl, _ = struct.unpack_from("<II", d, 12)
    return json.loads(d[20:20 + cl])


def node_local(n):
    if "matrix" in n:
        return np.array(n["matrix"], float).reshape(4, 4).T  # glTF column-major
    M = np.eye(4)
    if "translation" in n:
        M[:3, 3] = n["translation"]
    if "rotation" in n or "scale" in n:
        raise SystemExit("unexpected rotation/scale on source node " + n.get("name", "?"))
    return M


def mesh_bounds(g, mi):
    lo = np.full(3, np.inf)
    hi = np.full(3, -np.inf)
    for pr in g["meshes"][mi]["primitives"]:
        a = g["accessors"][pr["attributes"]["POSITION"]]
        lo = np.minimum(lo, a["min"])
        hi = np.maximum(hi, a["max"])
    return lo, hi


def build(gender):
    src = load_glb(SOURCES[gender])
    live = load_glb(LIVE[gender])
    nodes = src["nodes"]
    parent = {}
    for i, n in enumerate(nodes):
        for c in n.get("children", []):
            parent[c] = i
    world = {}

    def W(i):
        if i not in world:
            L = node_local(nodes[i])
            world[i] = (W(parent[i]) @ L) if i in parent else L
        return world[i]

    joints, parts, src_boxes = {}, {}, {}
    for i, n in enumerate(nodes):
        if "mesh" in n:
            j = nodes[parent[i]]["name"]
            parts[n["name"]] = j
            lo, hi = mesh_bounds(src, n["mesh"])
            M = W(i)
            src_boxes[n["name"]] = (M[:3, :3] @ lo + M[:3, 3], M[:3, :3] @ hi + M[:3, 3])
        else:
            joints[n["name"]] = {
                "parent": nodes[parent[i]]["name"] if i in parent else None,
                "p": W(i)[:3, 3].tolist(),
            }

    # Fit live = s * src + t on bbox corners (live meshes are world-space, no node transforms).
    A, b = [], []
    for n in live["nodes"]:
        name = n["name"]
        if name not in src_boxes:
            raise SystemExit(f"{gender}: live mesh {name} missing from source")
        llo, lhi = mesh_bounds(live, n["mesh"])
        slo, shi = src_boxes[name]
        for sv, lv in ((slo, llo), (shi, lhi)):
            for ax in range(3):
                row = [0.0] * 4
                row[0] = sv[ax]
                row[1 + ax] = 1.0
                A.append(row)
                b.append(lv[ax])
    sol, *_ = np.linalg.lstsq(np.array(A), np.array(b), rcond=None)
    s, t = sol[0], sol[1:]
    resid = np.abs(np.array(A) @ sol - np.array(b)).max()
    print(f"[{gender}] fit scale={s:.6f} offset={np.round(t, 5).tolist()} max_resid={resid*1000:.2f} mm")
    if resid > 0.002:
        raise SystemExit(f"{gender}: fit residual too large ({resid})")

    out_j = {}
    for name, j in joints.items():
        if name == "Root":
            continue
        p = s * np.array(j["p"]) + t
        out_j[name] = {"parent": None if j["parent"] in (None, "Root") else j["parent"],
                       "p": [round(float(v), 5) for v in p]}
    live_names = {n["name"] for n in live["nodes"]}
    out_parts = {k: v for k, v in parts.items() if k in live_names}
    print(f"[{gender}] joints={len(out_j)} parts={len(out_parts)} / live meshes={len(live_names)}")
    return {"joints": out_j, "parts": out_parts}


def main():
    data = {g: build(g) for g in ("male", "female")}
    body = json.dumps(data, separators=(",", ":"))
    OUT.write_text(
        "// GENERATED by tools/marco_char_delta/gen_rig_map.py — do not edit by hand.\n"
        "// Joint pivots (live GLB model space, metres) + mesh->joint map for Marco\n"
        "// build_characters iter2 male/female. Characters GLBs are unchanged.\n"
        f"export const CHAR_RIG_DATA = {body};\n"
    )
    print("wrote", OUT, OUT.stat().st_size, "bytes")


if __name__ == "__main__":
    main()
