"""Normalize Marco Belizean/Trinidadian build_characters turnaround GLBs for app13.

Keep character standing on Blender +Z (native up). glTF export_yup maps
Blender Z-up -> glTF Y-up. Do NOT pre-rotate to Y or export double-converts.
Scale to ~1.7m, feet on z=0, recalc normals, binary GLB.

Source: build_characters.py iteration 2 (delta4 *_build_v2.glb; fingers + detail; static
trimeshes, no skins/clips). This is the LIVE character set (shipped 838b703, restored by rollback
2b6cf49). Walk/run/idle are procedural at runtime (public/js/char_rig.js + char_rig_data.js,
generated by gen_rig_map.py from the same build_v2 joint trees), so the GLBs stay static.
orient_by_anchors() is a no-op for these upright files; it only matters for sideways imports.
Prior sources (NOT rebuilt): delta5 *_lowpoly.glb (rejected, rolled back), delta3 *_build.glb (iter1).
If you re-run this, re-run gen_rig_map.py afterwards and check the scale/offset fit it prints.
"""
import bpy
import shutil
from mathutils import Vector

TARGET_H = 1.7
OUT_DIR = "/workspace/app13-caribcrime/public/assets/characters"

JOBS = [
    (
        "/workspace/marco-char-delta4/male_belizean_build_v2.glb",
        f"{OUT_DIR}/male.glb",
        "male",
        f"{OUT_DIR}/male_belizean_build_v2.glb",
    ),
    (
        "/workspace/marco-char-delta4/female_trinidadian_build_v2.glb",
        f"{OUT_DIR}/female.glb",
        "female",
        f"{OUT_DIR}/female_trinidadian_build_v2.glb",
    ),
]


def clear_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)


def world_bounds(objs):
    mins = Vector((1e9, 1e9, 1e9))
    maxs = Vector((-1e9, -1e9, -1e9))
    for o in objs:
        for corner in o.bound_box:
            w = o.matrix_world @ Vector(corner)
            mins = Vector(tuple(min(a, b) for a, b in zip(mins, w)))
            maxs = Vector(tuple(max(a, b) for a, b in zip(maxs, w)))
    return mins, maxs


def apply_sel(meshes):
    bpy.ops.object.select_all(action="DESELECT")
    for o in meshes:
        o.select_set(True)
    bpy.context.view_layer.objects.active = meshes[0]
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    bpy.context.view_layer.update()


def ensure_z_up(meshes, label):
    """Blender glTF import usually yields Z-up; some files may already be Y-up in Blender.
    If tallest axis is Y (or X), rotate so standing height is on +Z before normalize.
    """
    mins, maxs = world_bounds(meshes)
    hx, hy, hz = (maxs - mins).x, (maxs - mins).y, (maxs - mins).z
    print(f"[{label}] pre-orient size X={hx:.3f} Y={hy:.3f} Z={hz:.3f}")
    if hz >= hx and hz >= hy:
        return  # already Z-up
    # Rotate so the tallest axis becomes +Z
    if hy >= hx and hy >= hz:
        # Y is up -> rotate -90° about X (Y -> Z)
        # glTF import uses QUATERNION rotation_mode, so rotate world matrices (not rotation_euler).
        # -90 about X maps (x, y, z) -> (x, z, -y); anchor check below fixes head-down if needed.
        print(f"[{label}] Y-tall detected; rotating -90 deg about X")
        _rot(meshes, "X", -1.5707963267948966)
        return
    elif hx >= hy and hx >= hz:
        print(f"[{label}] X-tall detected; rotating +90 deg about Y")
        _rot(meshes, "Y", 1.5707963267948966)
        return
    bpy.context.view_layer.update()
    apply_sel(meshes)


def _center(o):
    cs = [o.matrix_world @ Vector(c) for c in o.bound_box]
    return sum(cs, Vector()) / 8


def _find(meshes, *keys):
    """Match base names with optional male_/female_ prefix (e.g. head, male_head)."""
    out = []
    for o in meshes:
        n = o.name.lower().split(".")[0]
        for pre in ("male_", "female_"):
            if n.startswith(pre):
                n = n[len(pre):]
                break
        if any(n == k or n.startswith(k + "_") for k in keys):
            out.append(o)
    return out


def _rot(meshes, axis, angle):
    from mathutils import Matrix
    R = Matrix.Rotation(angle, 4, axis)
    for o in meshes:
        o.matrix_world = R @ o.matrix_world
    bpy.context.view_layer.update()
    apply_sel(meshes)


def orient_by_anchors(meshes, label):
    """Head above feet on +Z; nose in front of head on Blender -Y (= glTF +Z, MODEL_YAW_OFFSET 0)."""
    heads = _find(meshes, "head")
    feet = _find(meshes, "boot", "sole", "boot_sole", "boot_foot")
    noses = _find(meshes, "nose")
    if not (heads and feet and noses):
        print(f"[{label}] anchor meshes missing (head/boot/nose); skip anchor orient")
        return
    hc = _center(heads[0])
    fc = sum((_center(o) for o in feet), Vector()) / len(feet)
    if hc.z < fc.z:
        print(f"[{label}] head below feet; rotating 180 about Y")
        _rot(meshes, "Y", 3.141592653589793)
        hc = _center(heads[0])
    nc = _center(noses[0])
    d = nc - hc
    if abs(d.x) > abs(d.y):
        ang = 1.5707963267948966 if d.x > 0 else -1.5707963267948966
        print(f"[{label}] nose on X; rotating {ang:+.3f} about Z")
        _rot(meshes, "Z", ang)
    elif d.y > 0:
        print(f"[{label}] facing Blender +Y; rotating 180 about Z")
        _rot(meshes, "Z", 3.141592653589793)
    hc = _center(heads[0]); nc = _center(noses[0])
    fc = sum((_center(o) for o in feet), Vector()) / len(feet)
    mins, maxs = world_bounds(meshes)
    H = maxs.z - mins.z
    assert hc.z - fc.z > 0.5 * H, f"[{label}] head not clearly above feet (H={H:.3f})"
    assert hc.y - nc.y > 0.02 * H, f"[{label}] nose not clearly in front (-Y)"
    print(f"[{label}] anchor OK head_z={hc.z:.3f} feet_z={fc.z:.3f} nose-head_y={nc.y-hc.y:.3f} (faces glTF +Z)")


def process(src, dst, label):
    clear_scene()
    bpy.ops.import_scene.gltf(filepath=src)
    meshes = [o for o in bpy.context.scene.objects if o.type == "MESH"]
    if not meshes:
        raise RuntimeError(f"no meshes in {src}")

    # Drop empties — flatten so transforms live on meshes
    for o in list(bpy.context.scene.objects):
        if o.type != "MESH" and o.type != "CAMERA" and o.type != "LIGHT":
            for c in list(o.children):
                mw = c.matrix_world.copy()
                c.parent = None
                c.matrix_world = mw
            try:
                bpy.data.objects.remove(o, do_unlink=True)
            except Exception:
                pass

    meshes = [o for o in bpy.context.scene.objects if o.type == "MESH"]
    apply_sel(meshes)
    ensure_z_up(meshes, label)
    orient_by_anchors(meshes, label)

    mins, maxs = world_bounds(meshes)
    hx, hy, hz = (maxs - mins).x, (maxs - mins).y, (maxs - mins).z
    print(f"[{label}] raw size X={hx:.3f} Y={hy:.3f} Z={hz:.3f} minZ={mins.z:.3f}")
    if hz < hx or hz < hy:
        raise RuntimeError(f"[{label}] expected Z-up after import, got size {hx,hy,hz}")

    # Head size note (detect oversized / wrong head)
    for o in meshes:
        if o in _find(meshes, "head"):
            print(f"[{label}] head mesh dims={tuple(round(d, 4) for d in o.dimensions)} name={o.name}")

    scale = TARGET_H / hz
    for o in meshes:
        o.scale = (scale, scale, scale)
    bpy.context.view_layer.update()
    apply_sel(meshes)

    mins, maxs = world_bounds(meshes)
    dz = -mins.z
    for o in meshes:
        o.location.z += dz
    bpy.context.view_layer.update()
    apply_sel(meshes)

    for o in meshes:
        bpy.ops.object.select_all(action="DESELECT")
        o.select_set(True)
        bpy.context.view_layer.objects.active = o
        bpy.ops.object.mode_set(mode="EDIT")
        bpy.ops.mesh.select_all(action="SELECT")
        bpy.ops.mesh.normals_make_consistent(inside=False)
        bpy.ops.object.mode_set(mode="OBJECT")

    mins, maxs = world_bounds(meshes)
    print(
        f"[{label}] Blender FINAL H(z)={maxs.z-mins.z:.3f} minZ={mins.z:.3f} "
        f"size={(maxs-mins).x:.3f},{(maxs-mins).y:.3f},{(maxs-mins).z:.3f} meshes={len(meshes)}"
    )

    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.export_scene.gltf(
        filepath=dst,
        export_format="GLB",
        use_selection=False,
        export_apply=True,
        export_animations=False,
        export_skins=False,
        export_morph=False,
        export_yup=True,
    )
    print(f"[{label}] wrote {dst}")


def main():
    for src, dst, label, provenance in JOBS:
        process(src, dst, label)
        shutil.copyfile(dst, provenance)
        print(f"provenance {dst} -> {provenance}")
    shutil.copyfile(f"{OUT_DIR}/male.glb", f"{OUT_DIR}/player.glb")
    print("copied male.glb -> player.glb")


if __name__ == "__main__":
    main()
